require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProjectImagesController do

  def mock_project_image(stubs={})
    @mock_project_image ||= mock_model(ProjectImage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all project_images as @project_images" do
      ProjectImage.stub(:all) { [mock_project_image] }
      get :index
      assigns(:project_images).should eq([mock_project_image])
    end
  end

  describe "GET show" do
    it "assigns the requested project_image as @project_image" do
      ProjectImage.stub(:find).with("37") { mock_project_image }
      get :show, :id => "37"
      assigns(:project_image).should be(mock_project_image)
    end
  end

  describe "GET new" do
    it "assigns a new project_image as @project_image" do
      ProjectImage.stub(:new) { mock_project_image }
      get :new
      assigns(:project_image).should be(mock_project_image)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_image as @project_image" do
      ProjectImage.stub(:find).with("37") { mock_project_image }
      get :edit, :id => "37"
      assigns(:project_image).should be(mock_project_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created project_image as @project_image" do
        ProjectImage.stub(:new).with({'these' => 'params'}) { mock_project_image(:save => true) }
        post :create, :project_image => {'these' => 'params'}
        assigns(:project_image).should be(mock_project_image)
      end

      it "redirects to the created project_image" do
        ProjectImage.stub(:new) { mock_project_image(:save => true) }
        post :create, :project_image => {}
        response.should redirect_to(project_image_url(mock_project_image))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_image as @project_image" do
        ProjectImage.stub(:new).with({'these' => 'params'}) { mock_project_image(:save => false) }
        post :create, :project_image => {'these' => 'params'}
        assigns(:project_image).should be(mock_project_image)
      end

      it "re-renders the 'new' template" do
        ProjectImage.stub(:new) { mock_project_image(:save => false) }
        post :create, :project_image => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_image" do
        ProjectImage.stub(:find).with("37") { mock_project_image }
        mock_project_image.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :project_image => {'these' => 'params'}
      end

      it "assigns the requested project_image as @project_image" do
        ProjectImage.stub(:find) { mock_project_image(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:project_image).should be(mock_project_image)
      end

      it "redirects to the project_image" do
        ProjectImage.stub(:find) { mock_project_image(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(project_image_url(mock_project_image))
      end
    end

    describe "with invalid params" do
      it "assigns the project_image as @project_image" do
        ProjectImage.stub(:find) { mock_project_image(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:project_image).should be(mock_project_image)
      end

      it "re-renders the 'edit' template" do
        ProjectImage.stub(:find) { mock_project_image(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_image" do
      ProjectImage.stub(:find).with("37") { mock_project_image }
      mock_project_image.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the project_images list" do
      ProjectImage.stub(:find) { mock_project_image }
      delete :destroy, :id => "1"
      response.should redirect_to(project_images_url)
    end
  end

end
