require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProjectTagsController do

  def mock_project_tag(stubs={})
    @mock_project_tag ||= mock_model(ProjectTag, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all project_tags as @project_tags" do
      ProjectTag.stub(:all) { [mock_project_tag] }
      get :index
      assigns(:project_tags).should eq([mock_project_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested project_tag as @project_tag" do
      ProjectTag.stub(:find).with("37") { mock_project_tag }
      get :show, :id => "37"
      assigns(:project_tag).should be(mock_project_tag)
    end
  end

  describe "GET new" do
    it "assigns a new project_tag as @project_tag" do
      ProjectTag.stub(:new) { mock_project_tag }
      get :new
      assigns(:project_tag).should be(mock_project_tag)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_tag as @project_tag" do
      ProjectTag.stub(:find).with("37") { mock_project_tag }
      get :edit, :id => "37"
      assigns(:project_tag).should be(mock_project_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created project_tag as @project_tag" do
        ProjectTag.stub(:new).with({'these' => 'params'}) { mock_project_tag(:save => true) }
        post :create, :project_tag => {'these' => 'params'}
        assigns(:project_tag).should be(mock_project_tag)
      end

      it "redirects to the created project_tag" do
        ProjectTag.stub(:new) { mock_project_tag(:save => true) }
        post :create, :project_tag => {}
        response.should redirect_to(project_tag_url(mock_project_tag))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_tag as @project_tag" do
        ProjectTag.stub(:new).with({'these' => 'params'}) { mock_project_tag(:save => false) }
        post :create, :project_tag => {'these' => 'params'}
        assigns(:project_tag).should be(mock_project_tag)
      end

      it "re-renders the 'new' template" do
        ProjectTag.stub(:new) { mock_project_tag(:save => false) }
        post :create, :project_tag => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_tag" do
        ProjectTag.stub(:find).with("37") { mock_project_tag }
        mock_project_tag.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :project_tag => {'these' => 'params'}
      end

      it "assigns the requested project_tag as @project_tag" do
        ProjectTag.stub(:find) { mock_project_tag(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:project_tag).should be(mock_project_tag)
      end

      it "redirects to the project_tag" do
        ProjectTag.stub(:find) { mock_project_tag(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(project_tag_url(mock_project_tag))
      end
    end

    describe "with invalid params" do
      it "assigns the project_tag as @project_tag" do
        ProjectTag.stub(:find) { mock_project_tag(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:project_tag).should be(mock_project_tag)
      end

      it "re-renders the 'edit' template" do
        ProjectTag.stub(:find) { mock_project_tag(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_tag" do
      ProjectTag.stub(:find).with("37") { mock_project_tag }
      mock_project_tag.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the project_tags list" do
      ProjectTag.stub(:find) { mock_project_tag }
      delete :destroy, :id => "1"
      response.should redirect_to(project_tags_url)
    end
  end

end
